# (from: https://github.com/codecov/example-node/blob/master/.travis.yml)
language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
install:
  # Install tmpl
  - go get -u github.com/nwtgck/tmpl
script:
  # Fill variables by tmpl
  - tmpl fill --fill-yaml="{project_name: myproject, description: 'My Project', github_user: hogehogeuser, keywords: [http, server, example]}"
  - npm install
  - npm test
